// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Payroll.Models;

#nullable disable

namespace Payroll.Migrations
{
    [DbContext(typeof(ApplicationDbcontext))]
    [Migration("20230329041500_db created")]
    partial class dbcreated
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Payroll.Models.CreateSalaryClass", b =>
                {
                    b.Property<string>("ClassName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BasicPay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InternetAllowance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MedicalAlowance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TraverAllowance")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClassName");

                    b.ToTable("SalaryClass");
                });
#pragma warning restore 612, 618
        }
    }
}
